language: ruby
cache: bundler
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{drop,create,migrate} RAILS_ENV=test
- bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  api_key:
    secure: C+tqSDpvan42YZ63xSCHI8MYC6QdFEvXiNyKvz2IDGjlwXhrNA8q3MlsM1iiJkrbngymGvf3zQu3nzGTpPDwVhW8cUaj/ZfP1Rd2U6EC5wpsQ2psy2EkqoTs7L5FtR0Nil6E0+raZHh8M3ILpUJAbbfAIY4QR30rXiXdAYGFHu/2+IizkxpI85KDR2GBVAxcpCnXHdUBMsGW25YuhPqJXLZe2iOzL2YrpWV33IXZrfeszzpMVKooYr2kNqX2Qb8knf7deJlTvbWNnF3nm8ZRkNWbzmOBi0y7jRuvepqf1js/oJYmMlQw3y54cj0/A/uLhbHssohLA9Hx8R/k89bZTeLvcvjTlY6JDPKfDZzF46YVEmgAT816nPK156AQBORCPlQY/iZ2Nhr09Wu4HloVaVx5bAxvI7t1PMha2erh3hyDTqf+ipvPj5A/KPZ8oe3qBiF6Z5CT1EPJ05Z4MEi1cXrlMQVL6pP+SRlB+EmdRVzmkPkary4PvgokmJuoysihjjN/IawL6s/+XZyFNFYCZ05j1yhH0EyTjU2dAFjHRhByQ3lZns3QOd4T22XSeP0PSK+RDbG9wUQ3/8k2cD9zSes4VHXF1xBNn3nQEzeAdrWdaa66BAfmxB6iT6dO2MCYx0n15VlxIIes23lztG2k9j5982D76HoZNi2oU19ogfY=
